### ISSUE TITLE
Profile: Bundle

### ISSUE THREAD

**Issue by cander2** [HL7/vulcan-eproduct-info#29]
ePI's have two dates (1) date of first authorization; and (2) date of revision of the text. 

Any thoughts on how to handle this using the attributes?

Figure it makes sense to put these dates with the Bundle since it represents the document but an argument could be made for using the Composition.

**Comment by gcangioli** [comment]
The bundle.timestamp is when the bundle is assembled (and this is in any case required)
My suggestion is to rely on Composition dates..
My take on this is that the date of the last update can be represented by the [Composition.date](https://build.fhir.org/composition-definitions.html#Composition.date). _("The composition editing time, when the composition was last logically changed by the author.")_
the standard moreover says that _"the Last Modified Date on the composition may be after the date of the document was attested without being changed."_

**Comment by gcangioli** [comment]
Concerning the "date of first authorization" i see different options ...
(1) use a Provenance resource where the action is the "authorization"
(2) consider the authorization a kind of attestation and use the  [attester.time](https://build.fhir.org/composition-definitions.html#Composition.attester.time)
(3) use the [cqm-ValidityPeriod](https://build.fhir.org/extension-cqm-validityperiod.html) extension and consider the auth date as the date when the document started to be valid (note: the specification of this extension seems wrong it is a dateTime...)
(4) define an ad hoc extension

**Comment by gcangioli** [comment]
@cander2 : are both mandatory ?

**Comment by cander2** [comment]
The regulators will probably argue that it is mandatory since it has been a long-standing part of labels. Can be a very big deal in legal matters where you have to show what text was added when.

I like your idea though of using the bundle and composition dates as the last modified date.

To meet regulator requirements, I think we can make a case for them to use the Regulated Authorization to show the date of original authorization. For example, Validity Period is a period and can show the start date for the authorization.
