### ISSUE TITLE
Errors after updating IG .md files

### ISSUE THREAD

**Issue by cander2** [HL7/vulcan-eproduct-info#47]
Hey @jkiddo, @gcangioli,

Can you help? I tried restructure the IG's .md files to match the new table of contents. Getting these validation errors. Not sure what to do with this.
[gravitate-health](https://github.com/hl7-eu/gravitate-health)/[input](https://github.com/hl7-eu/gravitate-health/tree/master/input)/pagecontent/

Sushi: error Failed to load hl7.fhir.r5.core#5.0.0-snapshot1: The package hl7.fhir.r5.core#5.0.0-snapshot1 could not be loaded locally or from the FHIR package registry. (00:05.0127)
Sushi: error Valid StructureDefinition resource not found. The FHIR package in your local cache may be corrupt. Local FHIR cache can be found at <home-directory>/.fhir/packages. For more information, see https://wiki.hl7.org/FHIR_Package_Cache#Location. (00:05.0182)
Sushi couldn't be run. Complete output from running Sushi :                      (00:05.0192)
Note: Check that Sushi is installed correctly ("npm install -g fsh-sushi". On windows, get npm from https://www.npmjs.com/get-npm) (00:05.0192)
Exception: Process exited with an error: 1 (Exit value: 1)                       (00:05.0194)
Publishing Content Failed: Process exited with an error: 1 (Exit value: 1)       (00:05.0194)

**Comment by jkiddo** [comment]
I just checked the latest commit of yours. I think you were unlucky. It looks like it works again

**Comment by cander2** [comment]
Ok, I see it went through but not where it went. The pages deployment screens says it deployed here https://hl7-eu.github.io/gravitate-health/ but get 404 when clicking that link.

And the normal IG wasn't updated. Did it make a new page somewhere else?

**Comment by jkiddo** [comment]
Okay ... I looked into it - short story is: 'naming matters'. You have renamed all the *.md files which are referred from the https://github.com/hl7-eu/gravitate-health/blob/4fcc8a120edb23129e4fff6dbb0823419620fa73/sushi-config.yaml#L74 section. In short - everything works, but since you've renamed the files we no longer know what to refer to. eg. the previous index site was named index.md but since it doesn't exist anymore, the IG no longer knows where it starts

**Comment by jkiddo** [comment]
@cander2 if needed I can be available tomorrow around 10:00 your time and we can do a quick call.

**Comment by gcangioli** [comment]
dear both I saw that all the source pages have been renamed .. while the config.yaml has been not 
Could you help me to understand what it was supposed to be achieved ?

Do you want to have also the html pages renamed (maybe excluding index.html) or only the source file have to be renamed for management purposes, while the html pages could be the original ones.. ?

**Comment by cander2** [comment]
updated the .md files to fit newly adjusted structure. Any thoughts on how to fix these two errors?

Publishing Content Failed: Error parsing /github/workspace/fsh-generated/resources/CodeSystem-CodeSystemUvEPIRsmswi: Unsupported version 5.0.0-snapshot1 (00:50.010)
[120](https://github.com/hl7-eu/gravitate-health/runs/7492542340?check_suite_focus=true#step:5:121)
                                                                                 (00:50.012)
[121](https://github.com/hl7-eu/gravitate-health/runs/7492542340?check_suite_focus=true#step:5:122)
Use -? to get command line help                                                  (00:50.012)
[122](https://github.com/hl7-eu/gravitate-health/runs/7492542340?check_suite_focus=true#step:5:123)
                                                                                 (00:50.013)
[123](https://github.com/hl7-eu/gravitate-health/runs/7492542340?check_suite_focus=true#step:5:124)
Stack Dump (for debugging):                                                      (00:50.014)
[124](https://github.com/hl7-eu/gravitate-health/runs/7492542340?check_suite_focus=true#step:5:125)
java.lang.Exception: Error parsing /github/workspace/fsh-generated/resources/CodeSystem-CodeSystemUvEPIRsmswi: Unsupported version 5.0.0-snapshot1
