### ISSUE TITLE
Fix the guide menu and missing index page

### ISSUE THREAD

**Issue by gcangioli** [HL7/vulcan-eproduct-info#49]
- [x] most of the menu item (pages) are missing 
- [x] the structure doesn't correspond to the propose one
- [x] the index.html page is missing

**Comment by gcangioli** [comment]
First proposal in https://github.com/hl7-eu/gravitate-health/commit/8917665a5ca3b778d39ad29aa325d1a25a31995f

**Comment by gcangioli** [comment]
The structure of the guide (as FHIR IG) and of the included pages has to be further discussed

**Comment by cander2** [comment]
Updated the menus
