### ISSUE TITLE
IG rendering errors

### ISSUE THREAD

**Issue by cander2** [HL7/vulcan-eproduct-info#51]
Hey @jkiddo, @gcangioli,

Any thoughts on this error: https://github.com/hl7-eu/gravitate-health/actions/runs/2901075591? 

Everything appears to be rendering fine when I look at the markdown file. Seems to be something wrong when creating the IG's HTML pages. 
https://github.com/hl7-eu/gravitate-health/blob/master/input/pagecontent/steps-to-create-core-epi.md

**Comment by gcangioli** [comment]
> Hey @jkiddo, @gcangioli,
> 
> Any thoughts on this error: https://github.com/hl7-eu/gravitate-health/actions/runs/2901075591?
> 

@jkiddo  @cander2 : do we really need this part ? 
I don't think we are going to publish the CI build under the xyz.github.io site...

Suggest to remove this part

**Comment by jkiddo** [comment]
Right - we can delete the job for now -

**Comment by cander2** [comment]
everything came out fine in the new build after Lloyd moved it over
