### ISSUE TITLE
Update the sushi-config.yaml file 

### ISSUE THREAD

**Issue by gcangioli** [HL7/vulcan-eproduct-info#53]
Update at least the following parameters:
- [x] id .. It cannot be hl7.eu.fhir.gh it should be hl7.fhir.[REALM].[IG-ID]
- [x] canonical NOT http://hl7.eu/fhir/ig/gravitate-health but something like http://hl7.org/fhir/[REALM]/[IG-ID]
- [x] name (old GhImplementationGuide)
- [x] title (old Gravitate Health FHIR Implementation Guide)
- [x] publisher (old : Gravitate Health Project)
- [x] description:
- [x] check  license (now: CC0-1.0)

**Comment by gcangioli** [comment]
what is the IG id assigned ? is vulcan-eproduct-info ?

**Comment by gcangioli** [comment]
when the **_id_** is changed the "ig.ini" need to be updated as well...

**Comment by cander2** [comment]
> what is the IG id assigned ? is vulcan-eproduct-info ?

@gcangioli Yes, this is the IG id

**Comment by cander2** [comment]
> when the **_id_** is changed the "ig.ini" need to be updated as well...

Done. Updated ig.ini with correct IG id
