### ISSUE TITLE
IG publisher trying to use wrong FHIR version?

### ISSUE THREAD

**Issue by cander2** [HL7/vulcan-eproduct-info#54]
Just tried to publish (CI #356) a few profile and value set updates and got errors. Looks like it is trying to find the wrong version of FHIR. Did something switch or maybe I am doing something wrong?

Publishing Content Failed: Unknown FHIRVersion code '5.0.0-ballot'

**Comment by cander2** [comment]
Just realized the directory of FHIR versions is giving a 404. Guessing this is why the publishing job failed
http://hl7.org/fhir/uv/vulcan-epi/history.html

**Comment by cander2** [comment]
@jkiddo, @gcangioli, 
Graeme said we have to update the IG publisher (See Zulip chat below) because R5 broke the existing infrastructure. Can you help with this? No idea how to do this.

https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Unknown.20FHIRVersion.20code.20'5.2E0.2E0-ballot'/near/298291128

**Comment by gcangioli** [comment]
@cander2 usually this is done by running the __updatePublisher_ script.. but I suppose you did already :-)

**Comment by jkiddo** [comment]
@cander2 I'll remove our own build pipeline and just rely on the one provided by the community as I think it causes confusion.

**Comment by jkiddo** [comment]
@cander2 the history page is not the reason why you see the error

**Comment by cander2** [comment]
> 

Nope, don't even know what that is!

**Comment by cander2** [comment]
> @cander2 the history page is not the reason why you see the error

I'm not following what this means

**Comment by cander2** [comment]
> > @cander2 the history page is not the reason why you see the error
> 
> I'm not following what this means

Oh, ignore this. Forgot about my message about the page above. Now I follow.

**Comment by jkiddo** [comment]
Fixed with 2621437abd1227f9297c3648e0d361a48747b617

**Comment by jkiddo** [comment]
@cander2 FYI - since I’ve closed down our custom pipeline you can follow the status on https://chat.fhir.org/#narrow/stream/179297-committers.2Fnotification/topic/ig-build

**Comment by jkiddo** [comment]
@cander2 it looks like the tooling around 5.0.0-snapshot1 (which we are using) is now outdated by the tooling. We'll need to move up - most probably to 5.0.0-ballot which results in ~200 errors as the model have changed. Can you muster the needed forces in WP5 to help you out fixing those bugs? I will only update the IG to 5.0.0-ballot if you agree to it, but I honestly cannot see what else we should do.

**Comment by cander2** [comment]
> @cander2 it looks like the tooling around 5.0.0-snapshot1 (which we are using) is now outdated by the tooling. We'll need to move up - most probably to 5.0.0-ballot which results in ~200 errors as the model have changed. Can you muster the needed forces in WP5 to help you out fixing those bugs? I will only update the IG to 5.0.0-ballot if you agree to it, but I honestly cannot see what else we should do.

Wow, that’s a shame! Guess we don’t have much choice. 

Yes, updating the sample ePIs should be fine since we only really need one. More worried about the profile since that is harder to deal with.

ok, please go ahead. We’ll find a way to deal with the errors.

**Comment by jkiddo** [comment]
In a few minutes you should see this IG fail on https://chat.fhir.org/#narrow/stream/179297-committers.2Fnotification/topic/ig-build

**Comment by jkiddo** [comment]
@cander2 the lastest log is here: http://build.fhir.org/ig/HL7/vulcan-eproduct-info/branches/master/failure/build.log

**Comment by cander2** [comment]
> @cander2 the lastest log is here: http://build.fhir.org/ig/HL7/vulcan-eproduct-info/branches/master/failure/build.log

Thanks, got it. Going through it now

**Comment by cander2** [comment]
not too bad. Only 61 of the errors were for the profiles. Everything else was the ePI samples.
