### ISSUE TITLE
Changes for Organization

### ISSUE THREAD

**Issue by gcangioli** [HL7/vulcan-eproduct-info#58]
- [x]  contact add to all slices value 1..
- [x]  request at least one contact.address

**Comment by cander2** [comment]
Updated the profile and it was updated in GitHub but the IG wasn't updated due to this error:
http://build.fhir.org/ig/HL7/vulcan-eproduct-info/branches/master/failure/build.log 

Exception in thread "main" java.lang.Error: value is null

**Comment by cander2** [comment]
Corrected the error
