### ISSUE TITLE
Changes for Ingredient 

### ISSUE THREAD

**Issue by gcangioli** [HL7/vulcan-eproduct-info#59]
- [x] role add a binding ; define a value set ; SPOR preferred, NCI alternate
- [x] manufacturer.role leave unconstraint
- [x]  add SPOR example for substance code
- [x] substance code change to just CodeableReference no code only substanceDefinition
- [x] presentation[x] make slices for datatype and add binding for UCUM (preferred FHIR Valueset)
- [x] add elements under referenceStrength: susbstance as codeableReference, strength[x], measurementPoint and country

**Comment by cander2** [comment]
Going to need help with the presentation[x] part.

**Comment by cander2** [comment]
Decided to revert this back to the original presentation[x] in the base resource.
