### ISSUE TITLE
Changes for ManufacturedItemDefinition

### ISSUE THREAD

**Issue by gcangioli** [HL7/vulcan-eproduct-info#65]
- [x]  manufacturedDoseForm, unitOfPresentation remove the slice add binding to SPOR
- [x]  copy properties from administrableProduct

**Comment by cander2** [comment]
Removed the slice and added the binding.

**Comment by cander2** [comment]
[ ] How to make * property[image].value[x]     only Attachment reference a Binary or Attachment.data

Made the updates but don't understand how to make it a reference to a Binary resource in the Bundle. Or if that can't be done then make the image property Data so it is base64?

**Comment by costateixeira** [comment]
perhaps I'm out of context on this, but property.value[x] cannot be a
reference; it can be an attachment - in that case, the attachment.data will
contain the base-64.

**Comment by cander2** [comment]
> perhaps I'm out of context on this, but property.value[x] cannot be a reference; it can be an attachment - in that case, the attachment.data will contain the base-64.
> […](#)

Thanks. I updated it to .data
